services:
  web-kp:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: keypears-web-kp:latest
    container_name: keypears-app
    ports:
      - "4273:4273"
    environment:
      - NODE_ENV=production
      - PORT=4273
