services:
  postgres:
    image: postgres:17.5-alpine
    container_name: keypears-postgres
    ports:
      - "4275:5432"
    environment:
      POSTGRES_USER: keypears
      POSTGRES_PASSWORD: keypears_dev
      POSTGRES_DB: keypears
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  web-kp:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: web-kp/Dockerfile
      platforms:
        - linux/amd64
    image: keypears-web-kp:latest
    container_name: keypears-app
    ports:
      - "4273:4273"
    environment:
      - NODE_ENV=production
      - PORT=4273

volumes:
  postgres-data:
